[package]

name = "uuid"
version = "0.6.0-beta"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "https://docs.rs/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies.md5]
optional = true
version = "0.3"

[dependencies.rand]
optional = true
version = "0.4"

[dependencies.serde]
default-features = false
optional = true
version = "1.0.16"

[dependencies.sha1]
optional = true
version = "0.5"

[dev-dependencies]
serde_test = "1.0.19"

[features]
default = ["std"]
std = []
v1 = []
v3 = ["md5"]
v4 = ["rand"]
v5 = ["sha1"]

[target."cfg(all(feature = \"rand\", feature = \"std\"))".features]
std = ["rand/std"]

[target."cfg(all(feature = \"serde\", feature = \"std\"))".features]
std = ["serde/std"]

[target."cfg(all(feature = \"sha1\", feature = \"std\"))".features]
std = ["sha1/std"]
